### ISSUE TITLE
问个不关代码的，V10什么时候发

### ISSUE THREAD

**Issue by jianjianxu** [LyricTian/gin-admin#134]
感觉这个项目很好，纯后端插件简洁，结构清晰，没有那些花里胡哨的东西，非常适合做架子。
V8已经两年了，最近两年golang有点起飞了，看作者在更V10的版本，请问什么时候发正式版呢？

**Comment by LyricTian** [comment]
感谢关注，V10 的后端和 CLI 工具基本已经 ready，可以通过工具尝试一下，目前在迭代前端，十一之前能发出来，谢谢

**Comment by TZY0101** [comment]
> 感觉这个项目很好，纯后端插件简洁，结构清晰，没有那些花里胡哨的东西，非常适合做架子。 V8已经两年了，最近两年golang有点起飞了，看作者在更V10的版本，请问什么时候发正式版呢？

v9不是还没发么？

**Comment by jianjianxu** [comment]
> > 感觉这个项目很好，纯后端插件简洁，结构清晰，没有那些花里胡哨的东西，非常适合做架子。 V8已经两年了，最近两年golang有点起飞了，看作者在更V10的版本，请问什么时候发正式版呢？
> 
> v9不是还没发么？我看项目里的import都还是v8的包

有V10的，V9估计他没来得及

**Comment by jianjianxu** [comment]
> 感谢关注，V10 的后端和 CLI 工具基本已经 ready，可以通过工具尝试一下，目前在迭代前端，十一之前能发出来，谢谢
> 
> ```
> go clone https://github.com/gin-admin/gin-admin-cli.git -b feat/v10
> 
> cd gin-admin-cli && make build
> 
> gin-admin-cli new -d ~/go/src --name testapp --desc 'A test API service based on golang.' --module 'github.com/xxx/testapp' --git-branch 'feat/v10'
> ```
> 
> 

前端太泛了，框架无数个，更新速度快，半年一年就是一个新框架，我觉着专做go更好一点

**Comment by LyricTian** [comment]
嗯，前端框架确实很多，主要精力也是专注于后端这块，后面要做生态，专注于业务模块的构建，前端也是必不可少的一环。目前前端以 Ant Design Pro 作为主要的开发框架，再把相关文档完善好，后面就可以放开精力搞生态了。

**Comment by jianjianxu** [comment]
我们这边前端也是ant系

**Comment by Meepoljdx** [comment]
如果使用gin-admin-cli生成V10的业务模块的话，配置文件要写成这样，新版本貌似很多key都改了，失败的可以参考下，或者参照gin-admin-cli的Test测试文件自己写：
```yaml
- name: Cluster
  comment: 集群管理
  fields:
    - name: Name
      type: string
      comment: 名称
      json_tag: cluster_name
      custom_tag: mapstructure:"cluster_name"
      gorm_tag: column:cluster_name;unique;not null
    - name: Description
      type: string
      comment: 描述
      json_tag: description
      custom_tag: mapstructure:"description"
      gorm_tag: column:cluster_des
```
